# Generated by Django 4.1.7 on 2023-03-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TO_DO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='is_completed',
            field=models.CharField(max_length=50),
        ),
    ]
